package constant

const (
	LEAVE_APPROVE = "APPROVE"
	LEAVE_REJECT  = "REJECT"
)

const (
	ROLE_SUPER_ADMIN = "SUPERADMIN"
	ROLE_ADMIN       = "ADMIN"
	ROLE_EMPLOYEE    = "EMPLOYEE"
	ROLE_MANAGER     = "MANAGER"
	ROLE_HR          = "HR"
)
